services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=172.31.4.9:9094
      - KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME=connect
      - KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS=http://172.31.4.9:8083
      - KAFKA_CLUSTERS_0_SCHEMAREGISTRY=http://172.31.4.9:8081
    networks:
      - kafka-net
  
  kafka-lag-exporter:
    image: seglo/kafka-lag-exporter:0.6.9
    container_name: kafka-lag-exporter
    ports:
      - "8000:8000"
    volumes:
      - ./application.conf:/opt/docker/conf/application.conf
    networks:
      - kafka-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - kafka-lag-exporter
    networks:
      - kafka-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge